sudo: false

before_install:
 - 'path=`pwd`' 
 - 'git clone https://github.com/visze/simdrom.git simdrom'
 - 'cd simdrom'
 - 'git checkout development'
 - 'mvn --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dmaven.test.skip=true install'
 - 'cd $path'
 - 'mvn --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dmaven.test.skip=true test package'


language: java

jdk:
  - oraclejdk8
